# Site Settings
lang: en
title: Phylogeny and Physiology of the Human Microbiome
tagline: PhylHom Lab
email: your-email@domain.com
description: >
  Phylogeny and Physiology of the Human Microbiome INRAE Micalis website
baseurl: ""
url: ""
permalink: pretty
favicon: favicon.ico
# gh_sponsor: tapj
#hide_share_buttons: true
theme_color: '#9ed6e3'
fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname:

publisher: "PhylHom Lab"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from
  - jekyll-news-sitemap

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "PhylHom Lab"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  team:
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
    permalink: /team/:path/
  alumni:
    output: true
    permalink: /team/alumni/:path/
  projects:
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
  products:
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
